# Generated by Django 6.0 on 2025-12-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='input_variable_mappings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
