# Generated by Django 6.0 on 2025-12-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_node_input_variable_mappings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='global_arguments',
            field=models.JSONField(blank=True, default=dict, help_text='Global arguments accessible to all nodes'),
        ),
    ]
