# Generated by Django 6.0 on 2025-12-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pipeline_global_arguments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='global_arguments',
            field=models.JSONField(blank=True, default=list, help_text='Global argument names that will be prompted at execution'),
        ),
    ]
