# Generated by Django 6.0 on 2025-12-20 13:59

from django.db import migrations


def convert_dict_to_list(apps, schema_editor):
    """Convert global_arguments from dict format to list format"""
    Pipeline = apps.get_model('core', 'Pipeline')
    for pipeline in Pipeline.objects.all():
        if pipeline.global_arguments and isinstance(pipeline.global_arguments, dict):
            # Convert dict keys to list
            pipeline.global_arguments = list(pipeline.global_arguments.keys())
            pipeline.save(update_fields=['global_arguments'])


def convert_list_to_dict(apps, schema_editor):
    """Reverse migration - convert list back to dict (with empty values)"""
    Pipeline = apps.get_model('core', 'Pipeline')
    for pipeline in Pipeline.objects.all():
        if pipeline.global_arguments and isinstance(pipeline.global_arguments, list):
            # Convert list to dict with empty string values
            pipeline.global_arguments = {arg: '' for arg in pipeline.global_arguments}
            pipeline.save(update_fields=['global_arguments'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_change_global_arguments_to_list'),
    ]

    operations = [
        migrations.RunPython(convert_dict_to_list, convert_list_to_dict),
    ]
