# Generated by Django 6.0 on 2026-01-02 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_convert_global_arguments_dict_to_list'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nodeconnection',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='nodeconnection',
            name='from_node',
        ),
        migrations.RemoveField(
            model_name='nodeconnection',
            name='to_node',
        ),
        migrations.RemoveField(
            model_name='step',
            name='parent_step',
        ),
        migrations.RemoveField(
            model_name='step',
            name='pipeline',
        ),
        migrations.DeleteModel(
            name='UserDefinedFunction',
        ),
        migrations.RemoveField(
            model_name='node',
            name='input_variables',
        ),
        migrations.RemoveField(
            model_name='node',
            name='output_variables',
        ),
        migrations.RemoveField(
            model_name='node',
            name='status',
        ),
        migrations.DeleteModel(
            name='NodeConnection',
        ),
        migrations.DeleteModel(
            name='Step',
        ),
    ]
