# Generated by Django 6.0 on 2026-01-04 15:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_legacy_models_and_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentWorkspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Workspace name', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_code', models.TextField(default='# Write your planner here\n', help_text='agent.py file content')),
                ('agent_config', models.TextField(default="name: 'My Agent'\nobjective: ''\nallowed_tools: []\nconfig:\n  model: 'gpt-4o-mini'\n  temperature: 0.3\n  max_steps: 20\n", help_text='agent.yaml file content')),
                ('requirements', models.TextField(blank=True, help_text='requirements.txt file content (optional)')),
                ('validation_status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('error', 'Error'), ('pending', 'Pending Validation')], default='pending', max_length=20)),
                ('validation_errors', models.JSONField(blank=True, default=list, help_text='List of validation error messages')),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('planner_type', models.CharField(choices=[('deterministic', 'Deterministic'), ('llm', 'LLM-Based'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('planner_class_name', models.CharField(blank=True, help_text='Detected planner class name', max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pipeline', models.ForeignKey(blank=True, help_text='Associated pipeline (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_workspaces', to='core.pipeline')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('name', 'created_by')},
            },
        ),
    ]
