# Generated by Django 6.0 on 2026-01-03 07:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_remove_legacy_models_and_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('initializing', 'Initializing'), ('planning', 'Planning'), ('executing', 'Executing'), ('waiting_for_human', 'Waiting for Human'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='initializing', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent_config', models.JSONField(default=dict, help_text='Agent configuration: model, temperature, max_iterations, etc.')),
                ('current_step', models.IntegerField(default=0)),
                ('max_steps', models.IntegerField(default=100)),
                ('human_intervention_required', models.BooleanField(default=False)),
                ('human_intervention_reason', models.TextField(blank=True)),
                ('human_intervention_response', models.JSONField(blank=True, null=True)),
                ('pipeline_execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_run', to='core.pipelineexecution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.IntegerField()),
                ('decision_type', models.CharField(choices=[('plan', 'Initial Plan'), ('select_node', 'Node Selection'), ('evaluate_condition', 'Condition Evaluation'), ('handle_error', 'Error Handling'), ('request_human', 'Human Intervention Request'), ('finalize', 'Finalization')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.TextField(help_text='Prompt sent to LLM')),
                ('llm_response', models.TextField(help_text='Raw LLM response')),
                ('parsed_decision', models.JSONField(help_text='Structured decision output')),
                ('guardrail_violations', models.JSONField(default=list, help_text='Any guardrail violations detected')),
                ('guardrail_corrections', models.JSONField(default=list, help_text='Corrections applied by guardrails')),
                ('reasoning', models.TextField(blank=True, help_text="Agent's reasoning")),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('agent_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='agent_integration.agentrun')),
            ],
            options={
                'ordering': ['step_number', 'timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RuntimeSpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spec_version', models.CharField(default='1.0', max_length=20)),
                ('spec_data', models.JSONField(help_text='\n        Complete runtime specification including:\n        - available_tools: list of tool definitions\n        - execution_constraints: DAG constraints, dependencies\n        - business_conditions: conditional execution rules\n        - global_context: pipeline-level variables\n        ')),
                ('spec_checksum', models.CharField(max_length=64)),
                ('agent_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='runtime_spec', to='agent_integration.agentrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('tool_name', models.CharField(max_length=255)),
                ('tool_parameters', models.JSONField(default=dict)),
                ('result_summary', models.TextField(blank=True, help_text='Human-readable summary for agent consumption')),
                ('artifact_references', models.JSONField(default=list, help_text='List of artifact IDs/paths produced')),
                ('agent_decision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_executions', to='agent_integration.agentdecision')),
                ('agent_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_executions', to='agent_integration.agentrun')),
                ('node_execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tool_execution', to='core.nodeexecution')),
            ],
            options={
                'ordering': ['queued_at'],
            },
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['status', '-created_at'], name='agent_integ_status_a7dae2_idx'),
        ),
        migrations.AddIndex(
            model_name='agentdecision',
            index=models.Index(fields=['agent_run', 'step_number'], name='agent_integ_agent_r_7ad3ef_idx'),
        ),
        migrations.AddIndex(
            model_name='toolexecution',
            index=models.Index(fields=['agent_run', 'status'], name='agent_integ_agent_r_ea7853_idx'),
        ),
    ]
