# Generated by Django 6.0 on 2026-01-04 05:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_integration', '0001_initial'),
        ('core', '0006_remove_legacy_models_and_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('max_steps', models.IntegerField(default=100, help_text='Maximum number of decision steps before termination')),
                ('max_retries', models.IntegerField(default=3, help_text='Maximum consecutive failures before giving up')),
                ('require_human_approval', models.BooleanField(default=False, help_text='Pause execution and wait for human approval')),
                ('retry_policy', models.JSONField(default=dict, help_text='Retry configuration: backoff, conditions, etc.')),
                ('guardrail_config', models.JSONField(default=dict, help_text='Guardrail enforcement settings: loop detection, deadlock prevention, etc.')),
                ('llm_model', models.CharField(default='fallback-ordering', help_text="LLM model identifier or 'fallback-ordering' for deterministic mode", max_length=100)),
                ('llm_temperature', models.FloatField(default=0.0, help_text='Temperature for LLM sampling (0.0 = deterministic)')),
                ('llm_config', models.JSONField(default=dict, help_text='Additional LLM configuration parameters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('condition_type', models.CharField(choices=[('artifact_exists', 'Artifact Exists'), ('value_comparison', 'Value Comparison'), ('pattern_match', 'Pattern Match'), ('custom', 'Custom Logic')], max_length=50)),
                ('condition_config', models.JSONField(help_text='Configuration for condition evaluation')),
                ('test_cases', models.JSONField(default=list, help_text='List of test cases with inputs and expected outputs')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', '-version'],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='AgentConditionBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evaluation_point', models.CharField(choices=[('before_execution', 'Before Execution'), ('after_tool', 'After Each Tool'), ('on_failure', 'On Failure'), ('on_completion', 'On Completion')], default='before_execution', max_length=50)),
                ('parameters', models.JSONField(default=dict, help_text='Parameters to pass to condition evaluator')),
                ('on_true_action', models.CharField(choices=[('continue', 'Continue'), ('skip_tool', 'Skip Tool'), ('pause', 'Pause for Human'), ('terminate', 'Terminate')], default='continue', max_length=50)),
                ('on_false_action', models.CharField(choices=[('continue', 'Continue'), ('skip_tool', 'Skip Tool'), ('pause', 'Pause for Human'), ('terminate', 'Terminate')], default='continue', max_length=50)),
                ('max_evaluations', models.IntegerField(blank=True, help_text='Maximum times this condition can be evaluated (null = unlimited)', null=True)),
                ('priority', models.IntegerField(default=0, help_text='Evaluation order (higher = evaluated first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_bindings', to='agent_integration.agentprofile')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_bindings', to='agent_integration.businesscondition')),
            ],
            options={
                'ordering': ['-priority', 'condition__name'],
            },
        ),
        migrations.CreateModel(
            name='ToolDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('executor_type', models.CharField(choices=[('node', 'Pipeline Node'), ('function', 'Python Function'), ('external', 'External API')], default='node', max_length=20)),
                ('input_schema', models.JSONField(help_text='JSON Schema defining required/optional inputs')),
                ('output_schema', models.JSONField(help_text='JSON Schema defining expected outputs')),
                ('node_name', models.CharField(blank=True, help_text='Name of the node in the pipeline', max_length=255)),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this tool is available for agent use')),
                ('estimated_duration_seconds', models.IntegerField(blank=True, help_text='Estimated execution time for planning', null=True)),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost per execution', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline', models.ForeignKey(blank=True, help_text='Pipeline containing the backing node', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pipeline')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgentToolMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_allowed', models.BooleanField(default=True, help_text='Whether agent can use this tool')),
                ('max_calls', models.IntegerField(blank=True, help_text='Maximum calls per execution (null = unlimited)', null=True)),
                ('priority', models.IntegerField(default=0, help_text='Priority for tool selection (higher = preferred)')),
                ('prerequisites', models.JSONField(default=list, help_text='List of tool names that must execute first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_mappings', to='agent_integration.agentprofile')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_mappings', to='agent_integration.tooldefinition')),
            ],
            options={
                'ordering': ['-priority', 'tool__name'],
            },
        ),
        migrations.AddIndex(
            model_name='agentprofile',
            index=models.Index(fields=['status', 'name'], name='agent_integ_status_e7a8cf_idx'),
        ),
        migrations.AddIndex(
            model_name='agentconditionbinding',
            index=models.Index(fields=['agent', 'is_enabled'], name='agent_integ_agent_i_e30cee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentconditionbinding',
            unique_together={('agent', 'condition', 'evaluation_point')},
        ),
        migrations.AddIndex(
            model_name='agenttoolmapping',
            index=models.Index(fields=['agent', 'is_allowed'], name='agent_integ_agent_i_e977d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agenttoolmapping',
            unique_together={('agent', 'tool')},
        ),
    ]
