# Generated by Django 6.0 on 2026-01-04 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_integration', '0002_agentprofile_businesscondition_agentconditionbinding_and_more'),
        ('core', '0007_agentworkspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='last_validated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last workspace validation', null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='validation_errors',
            field=models.JSONField(blank=True, default=list, help_text='Validation error messages from workspace loader'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'Pending Validation'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('error', 'Validation Error')], default='pending', help_text='Result of last workspace validation', max_length=20),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='Workspace containing agent.py and agent.yaml (CANONICAL SOURCE)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='control_plane_agents', to='core.agentworkspace'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='workspace_version_hash',
            field=models.CharField(blank=True, help_text='Hash of workspace content at last validation/materialization', max_length=64),
        ),
    ]
