"""
Example migration file for agent_integration models.

Run: python manage.py makemigrations agent_integration
"""

# This file is just documentation. Actual migration will be generated by Django.

# To create the migration:
# 1. Add 'agent_integration' to INSTALLED_APPS in settings.py
# 2. Run: python manage.py makemigrations agent_integration
# 3. Run: python manage.py migrate agent_integration
